### ISSUE TITLE
Ocultar barras de scroll en firefox y edge

### ISSUE THREAD

**Issue by Mel-A** [Mel-A/lapse#27]
```css
.no-scrollbar::-moz-scrollbar {display:none;}
```
Esto no funciona,
